### ISSUE TITLE
Unable to send picture

### ISSUE THREAD

**Issue by dano6** [powerjungle/fbridge-asyncio#2]
I made today bridge between Telegram and Messenger using matterbridge.
Everything is working fine, but I am unable to send pictures. Receiving of images is working.

`INFO:root:From api received json: {'text': '', 'channel': '-************', 'username': '', 'userid': '***********', 'avatar': '', 'account': 'telegram.messenger', 'event': '', 'protocol': 'telegram', 'gateway': 'Veronika', 'parent_id': '', 'timestamp': '2021-01-24T20:25:32.017259209+01:00', 'id': '', 'Extra': {'file': [{'Name': 'photo_2021-01-24_20-24-57.jpg', 'Data': '  ........ Here was the data ......', 'Comment': 'test', 'URL': '', 'Size': 0, 'Avatar': False, 'SHA': ''}]}}
INFO:root:From api sending message: username:  | text: 
ERROR:root:#1545023 Správa sa nedá poslať: Zdá sa, že sa pokúšate poslať prázdnu správu. Napíšte svoju správu a skúste to znova.
`

That error is talking that I am trying to send empty message

**Comment by powerjungle** [comment]
Sorry for the delay! I'll look into it, I think I know what the cause is.

**Comment by powerjungle** [comment]
@dano6 The latest commit: 0e8957493601e7b7c125e849fd82245ff1403d89 should've fixed the issue. Pull the new changes rerun everything and let me know if it's fixed.

**Comment by dano6** [comment]
Great, it works!
